liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    filter_sets: # Contient la liste des filtres
        carre: # Nom du filtre
            quality: 85 # Qualité de l'image
            filters: # Liste des filtres à appliquer
                scale: # Filtre "Thumbnail"
                    dim: [100, 100] # Taille de l'image de sortie
                